# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chapter08-APITest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  # Pods for Chapter08-APITest

end
